test:
  image: node
  services:
    - postgres
    - rabbitmq:management
  variables:
    POSTGRES_DB: "zion_test"
    DATABASE_URL: "postgres://postgres@postgres:5432/zion_test"
    PORT: "4000"
  before_script:
    - npm i
    - node db/migrate.js
  script:
    - npm run test
    - npm run integration

staging:
  type: deploy
  image: ruby:latest
  script:
  - gem install dpl
  - dpl --provider=heroku --app=zionapi-staging --api-key=$HEROKU_STAGING_API_KEY
  except:
  - master

production:
  type: deploy
  image: ruby:latest
  script:
  - gem install dpl
  - dpl --provider=heroku --app=zionapi --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master
