image: docker

services:
  - docker:dind

test:
  before_script:
    - apk add --update py-pip
    - pip install docker-compose
    - docker-compose -v
    - docker-compose up -d
    - apk add --update nodejs
    - npm i
  script:
    - npm run test
    - find ./integration -name '*Test.js' | xargs mocha -R spec

production:
  type: deploy
  image: ruby:latest
  script:
  - gem install dpl
  - dpl --provider=heroku --app=zionapi --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master
