image: docker

services:
  - docker:dind

test:
  variables:
    DATABASE_URL: "postgres://postgres@127.0.0.1:5433/postgres"
    PORT: "4000"
  before_script:
    - apk add --update py-pip
    - pip install docker-compose
    - docker-compose -v
    - docker-compose up -d
    - docker ps
    - sleep 5
    - docker ps
    - apk add --update nodejs
    - npm i
    - docker ps
  script:
    - npm run test
    - npm run integration
    - find ./integration -name '*Test.js' | xargs mocha -R spec

production:
  type: deploy
  image: ruby:latest
  script:
  - gem install dpl
  - dpl --provider=heroku --app=zionapi --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master
