image: docker

services:
  - docker:dind

test:
  image: node:latest
  before_script:
    - docker-compose -v
    - docker-compose up -d
    - npm i
  script:
    - npm run test

production:
  type: deploy
  image: ruby:latest
  script:
  - gem install dpl
  - dpl --provider=heroku --app=zionapi --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master
