language: node_js
node_js:
  - "node"
sudo: required
services:
  - docker
install:
  - npm install
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose up -d
  - node db/migrateSeeds.js
env:
  global:
    - DATABASE_URL=postgres://postgres@127.0.0.1:5433/postgres
    - PORT=4000
script:
  - docker exec zionapi_db npm run test
