language: node_js
node_js:
  - node
sudo: required
services:
  - docker
install:
  - npm install
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose up -d
  - docker ps
  - node db/migrateSeeds.js
env:
  global:
    - DATABASE_URL=postgres://postgres@127.0.0.1:5433/postgres
    - PORT=4000
  # google maps api key
    - secure: gxsMTgk9sWWS40E9I9LVtpmGnhYQOc3OnJEEvGN3Lh3qr/ejVfbnQXbHU+qUoN93RmXdzbA/mdQAvJ2S7HB4p71JvP5kXF+YJnCf8pJ32FpXNplzDXZjuRNilA9Bxy78Pa4Y4zoDi6TXl0xgHEKFnQOWj9eJvGMd6+LZiqidtX2wkO/3HdNxQLAT/sjZOUnRaX2KGec0sopDiKa95QIo7TMs8RjD6u/aWGZSIBRPqnVevD44uYeTsqaMeP7WI17rG6wPqZzHdb5YCCKlwR4nLWoGpNIPSauLtcUUmr5s7V1J8pj/4hTSM+Kc+yPQPn4BYQxqoHQ8CVr+G1IBmNgo2pCR+jmSmwph3qsnHorXpHbKzUiDqszf4fLBGAYAwqKmlV5DBTx7WRma6ECVN67VUtrkGtvZGBOfGcphfO+r66uSjbrKQTZTjQHNKFIhlfJk9/HONWeDz6epcaC/CG7Y/NzeqFsh9f6lh294aNORZCoAnWbCoItRolf5ajUovneMzMY86oVURRaNLtJF5TDndx0MvH48hUC6mGCC0uliKg2DsFLiZETh2+AUHhsY5wAU6z4E2ezoiF4/gfVYuNWU2RQvjzti5ToNS09oW+wBBVbEYhfLKSwj4soKCHghwl7CqBVpulI1snV83Gc6bAc0jgVBo916HG8/JjVRE+17Prs=
script:
  - find ./integration -name '*Test.js' | xargs mocha -R spec
  - npm test
