version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=zion
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: zionapi_db
    ports:
      - '5433:5432'
  rabbitmq:
    image: rabbitmq:management
    container_name: zionapi_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
