version: '2'
services:
  db:
    image: postgres
    container_name: zionapi_db
    ports:
      - '5433:5432'
  rabbitmq:
    image: rabbitmq:management
    container_name: zionapi_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
